travis:
  secure:
    BINSTAR_TOKEN: XOYk4rhseCeSJJ/VxLKwswKmiXuQAiPkNDLRCQyEl380N2Vrh9vDcU6xlvSEYz+P/WF1qIeqpBbSReGMCGvg5MlPT+/25f0QXxJIrD2HQh3gYcmtmwVniqv26hgytYEVNeOoIaq1NI7R5QkiTu3L5Gk+410nHB/O+Okht5NpvRvECV33hZqtSyv5FJU97tMMrCJ1R1AQot8rUArHHxN4Uuhzv17dhsoVUR63o47SYKcaDA7IA1n7eFTX7fSSQKRQM24zzmZcOlY2rhQUmlWXnJEgqPCxV03xx9KRuCwf92XF2zPDXAMvBx21KlYEP6CeX6p+S7y/nK6i9xWnYIUiTYMfyBMOmRF+cuqtmWHyt/hSVoRo9HYl/TG0EfCj2FkXRj+KZAYwrBhVQWbdPPoZP1x1rJ0PjW1kosVsxPLrKhZHckDyrIbqVvHZCYAhResTExq2I14tAdND+wakOII2an6BRh0LUafeFRsjCWL2zSgk4djo+Tw5rpU23NIIwZL7Q119Gk8VvGwyPSUZ+4bo6w3GMMzV17Yzv+Qh5aBMreFsGzPwcefxPrUiaLPQo2jKoNWfH4JD+q+HQ/B4MEcx2a9+BwIvg1YBp0o85F/cabQxjUPQ9xEXx59ABp/DAkUUzEi2ozL1covEOOmZzLytuPp+ym/+u0x3tRWK0N4ka+A=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
